select * from public.resource_table;


INSERT INTO RESOURCE_TABLE VALUES (1,1,current_timestamp,'Sandeep',current_timestamp,'Mardolkar',TRUE);

INSERT INTO ROLE_TABLE VALUES (1,'LEAVE_ADMIN');
INSERT INTO ROLE_TABLE VALUES (2,'LEAVE_APPROVER');

--INSERT INTO RESOURCE_ROLES_TABLE VALUES (1,1);
--INSERT INTO RESOURCE_ROLES_TABLE VALUES (1,2);